### ISSUE TITLE
False positive for startsWith

### ISSUE THREAD

**Issue by ptarjan** [HappySale/eslint-plugin-parse#5] opened 2015-10-07 20:36 UTC
I have a line of code

```
if (_.startsWith(text, prefix)) {
```

which uses `lodash`'s `startsWith` method, but I get the error:

```
57 col 13 warning| `Parse.Query#startsWith()` it's a slow query that can cause timeouts (parse/no-slow-query) [javascript/eslint]
```

Can you be a little smarter on what the method is being called on?

**Comment by oriSomething** [comment] 2015-10-07 21:21
yes and no. i need to dive in more deeply to `ESLint` to give a better answer.
in early stages of tries i found that being **smart** might be also **slow**. so many "smart" checks became stupid. but it's bad if there is a collusion with `lodash`'s methods.
the problem is that technically, both options are possible:

``` js
// 1
const _ = new Parse.Query(···);
_.startsWith(···);

// 2
function weirdWayToQuery(query) {
  query.startsWidth(···);
}
```

if you have any ideas (exclude black/white list) i'll be happy to hear

**Comment by ptarjan** [comment] 2015-10-07 21:23
Can you track variable assignment from the `Parse.Query` and only run the check on those? I'd be happier with more false negatives (only catch the simple assign to variables and then query them) then more false positives.

The other option is to split it into two rules. One that is aggressive and disabled by default and one that is cautious and always on.

**Comment by oriSomething** [comment] 2015-10-07 21:28
i also thought about the first option. i need more to think if i'll consider cases for `const { Query } = Parse;` or `const ParseQuery = Parse.Query`...

i'll try to sit on it tomorrow and see how i fix this

**Comment by oriSomething** [comment] 2015-10-21 16:33
@ptarjan can you please check the PR to see if it resolve the problem?
i made a little hack over there so it suppose to only apply to direct call on `new Parse.Query` or a variable **name** that assigned to a `new Parse.Query`

**Comment by ptarjan** [comment] 2015-10-21 19:27
how do I check?

**Comment by oriSomething** [comment] 2015-10-21 20:54
``` sh
npm i --save-dev git+ssh://git@github.com/HappySale/eslint-plugin-parse.git#dffd066d5c58b7075036b285cd0256ac53dd4d9e

```

for the version with the fix. if it's okay, i'll publish a new version to NPM

**Comment by oriSomething** [comment] 2015-10-25 13:29
@ptarjan can you confirm the issue has being solved?

**Comment by ptarjan** [comment] 2015-10-25 20:07
I'm on vacation this week sadly so I'll check next week when I'm back

**Closed as completed** 2015-11-11 10:05 UTC
